//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_status")]
pub enum OrderStatus {
    #[sea_orm(string_value = "new")]
    New,
    #[sea_orm(string_value = "resting")]
    Resting,
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "canceled")]
    Canceled,
    #[sea_orm(string_value = "rejected")]
    Rejected,
}
