//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::Side;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "trade")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub market_id: Uuid,
    pub sequence: i64,
    pub maker_order_id: Uuid,
    pub taker_order_id: Uuid,
    pub maker_side: Option<Side>,
    pub tick: i64,
    pub quantity: i64,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::market::Entity",
        from = "Column::MarketId",
        to = "super::market::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Market,
    #[sea_orm(
        belongs_to = "super::order::Entity",
        from = "Column::MakerOrderId",
        to = "super::order::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Order2,
    #[sea_orm(
        belongs_to = "super::order::Entity",
        from = "Column::TakerOrderId",
        to = "super::order::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Order1,
}

impl Related<super::market::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Market.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
